name: gherapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  carousel_slider: ^5.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/logo.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/splashLogo.png
    - assets/headerLogo.png
    - assets/heroBanner.jpg
    - assets/property1.jpg
    - assets/property2.jpg
    - assets/property3.jpg
    - assets/profilePic.png
    - assets/icons/icon_144.png
    - assets/icons/icon_192.png
    - assets/icons/icon_512.png
